-- Tabel untuk menyimpan riwayat broadcast
create table if not exists public.broadcast_history (
  id bigint generated by default as identity primary key,
  message_text text not null,
  target_type text not null default 'all', -- 'all', 'active', 'filter'
  target_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  status text not null default 'pending', -- 'pending', 'sending', 'completed', 'failed', 'cancelled'
  created_by uuid references public.admin_users(id),
  created_at timestamp with time zone default now(),
  completed_at timestamp with time zone,
  error_message text
);

-- Tabel untuk detail broadcast per user
create table if not exists public.broadcast_recipients (
  id bigint generated by default as identity primary key,
  broadcast_id bigint not null references public.broadcast_history(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  telegram_id text not null,
  status text not null default 'pending', -- 'pending', 'sent', 'failed', 'delivered'
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- Tabel untuk template pesan
create table if not exists public.broadcast_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  content text not null,
  created_by uuid references public.admin_users(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Index untuk query cepat
create index if not exists idx_broadcast_history_status on public.broadcast_history(status);
create index if not exists idx_broadcast_history_created_at on public.broadcast_history(created_at desc);
create index if not exists idx_broadcast_recipients_broadcast_id on public.broadcast_recipients(broadcast_id);
create index if not exists idx_broadcast_recipients_status on public.broadcast_recipients(status);
create index if not exists idx_broadcast_templates_created_by on public.broadcast_templates(created_by);

-- RLS Policy (enable tapi allow all untuk service role)
alter table public.broadcast_history enable row level security;
alter table public.broadcast_recipients enable row level security;
alter table public.broadcast_templates enable row level security;

-- Comments
comment on table public.broadcast_history is 'Riwayat broadcast message ke users';
comment on table public.broadcast_recipients is 'Detail status broadcast per user';
comment on table public.broadcast_templates is 'Template pesan broadcast yang tersimpan';
