-- Table: transaksi_piutang
-- Menyimpan riwayat pembayaran piutang per transaksi

create table if not exists public.transaksi_piutang (
  id bigint generated by default as identity primary key,
  transaksi_id bigint not null references public.transaksi(id) on delete cascade,
  nominal_bayar integer not null default 0,
  tanggal_bayar timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- Index untuk query cepat
create index if not exists idx_transaksi_piutang_transaksi_id on public.transaksi_piutang(transaksi_id);
create index if not exists idx_transaksi_piutang_created_at on public.transaksi_piutang(created_at);

-- RLS Policy
alter table public.transaksi_piutang enable row level security;

create policy "Users can view their own transaksi_piutang"
  on public.transaksi_piutang for select
  using (
    exists (
      select 1 from public.transaksi
      where transaksi.id = transaksi_piutang.transaksi_id
      and transaksi.user_id = auth.uid()
    )
  );

create policy "Users can insert their own transaksi_piutang"
  on public.transaksi_piutang for insert
  with check (
    exists (
      select 1 from public.transaksi
      where transaksi.id = transaksi_piutang.transaksi_id
      and transaksi.user_id = auth.uid()
    )
  );

-- Comment
comment on table public.transaksi_piutang is 'Riwayat pembayaran piutang per transaksi';
comment on column public.transaksi_piutang.nominal_bayar is 'Nominal yang dibayar';
comment on column public.transaksi_piutang.tanggal_bayar is 'Tanggal pembayaran dilakukan';